spring.application.name=bankaccount
# Database Connection
spring.datasource.url=jdbc:postgresql://localhost:5433/banking_db
spring.datasource.username=user
spring.datasource.password=password
spring.datasource.driver-class-name=org.postgresql.Driver

# Schema Initialization (Connects schema.sql)
spring.sql.init.mode=always
spring.sql.init.platform=postgres

# RabbitMQ Connection
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

# MyBatis Settings
mybatis.mapper-locations=classpath:mappers/*.xml
mybatis.type-aliases-package=com.bankapplication.model